/**
 * @description       : Tests GetRelatedContacts
 * @author            : Charles Gallagher
 * @last modified on  : 06-07-2021
 * @last modified by  : Charles Gallagher
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   06-07-2021   Charles Gallagher  Initial Version
**/
@isTest
public class GetRelatedContactsTest 
{
	static testMethod void getContactsTest()
    {
        
    }
}